### ISSUE TITLE
IC-9700 on some languages it may require . instead of , for frequency decimal separator

### ISSUE THREAD

**Issue by iw3row** [LarsThunberg/SatelliteConfigurationFiles#1]
Tried on Italian language system, requires dot "." instead of comma "," for frequency decimal separator or CS-9700 gives import error (version 1.31)
Attached file works fine for me, just in case anyone else has the same issue.

[IC-9700_SatFrqMemGroup.csv](https://github.com/LarsThunberg/SatelliteConfigurationFiles/files/8407833/IC-9700_SatFrqMemGroup.csv)

         Thanks, Mauro IW3ROW

**Comment by LarsThunberg** [comment]
Thank you Mauro!
